#Backend
FROM golang:1.17-alpine AS build
WORKDIR /backend
COPY go.mod go.sum ./
COPY main.go ./
RUN go main.go

EXPOSE 3000

#Frontend
FROM node:16-alpine AS frontend
WORKDIR /frontend/client
COPY package.json package-lock.json ./
COPY src ./src
RUN npm run start

FROM alpine:latest

WORKDIR /Proyecto
COPY --from=backend /Proyecto/backend .
COPY --from=frontend /Proyecto/frontend/client ./frontend/client

EXPOSE 8090


CMD ["npm", "run", "start"]