version: '3'

services:
  dbmysql:
    build: ./Database
    environment:
      MYSQL_DATABASE: arqsoft
      MYSQL_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - /docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./frontend/client
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    depends_on:
      dbmysql:
        condition: service_healthy
    ports:
      - "8090:8090"
